networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"

services:
    apache1:
        networks:
            public_net:
                ipv4_address: "192.168.0.11"
    
    apache2:
        networks:
            public_net:
                ipv4_address: "192.168.0.22"
    
    haproxy:
        networks:
            public_net:
                ipv4_address: "192.168.0.33"